#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHome.Models.DataEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CA")]
	public partial class UXCADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCA(CA instance);
    partial void UpdateCA(CA instance);
    partial void DeleteCA(CA instance);
    #endregion
		
		public UXCADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UXCADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UXCADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UXCADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CA> CAs
		{
			get
			{
				return this.GetTable<CA>();
			}
		}
		
		public System.Data.Linq.Table<CA_TEMP> CA_TEMPs
		{
			get
			{
				return this.GetTable<CA_TEMP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CA")]
	public partial class CA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CA_ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _PASSCODE;
		
		private string _EMAIL;
		
		private string _JOB_TITLE;
		
		private string _EMPLOYEE_ID;
		
		private string _COUNTRY;
		
		private string _DUNS;
		
		private int _APPLY_STATE;
		
		private int _SEND_FLAG;
		
		private string _ERROR_CODE;
		
		private string _STATE;
		
		private string _LOCALITY;
		
		private int _CA_CLASS_ID;
		
		private System.DateTime _CREATION_TIME;
		
		private System.Nullable<System.DateTime> _APPLY_TIME;
		
		private System.Nullable<System.DateTime> _CA_FALL_TIME;
		
		private System.Nullable<bool> _MAIL_SEND_FLAG;
		
		private System.Nullable<bool> _ERROR_SEND_MAIL_FLAG;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _USER_SEX;
		
		private string _COMPANY_NAME;
		
		private string _COMPANY_ADDRESS;
		
		private string _COMPANY_TEL;
		
		private string _COMPANY_EXTENSION;
		
		private string _COMPANY_FAX;
		
		private string _INV_COMPANY_NAME;
		
		private string _INV_COMPANY_ADDRESS;
		
		private string _INV_EMPLOYEE_ID;
		
		private string _USER_MOBILE;
		
		private System.Nullable<System.DateTime> _USER_BIRTHDAY;
		
		private System.Nullable<short> _COMPANY_CLASS;
		
		private bool _CHECKED_FLAG;
		
		private string _PID;
		
		private string _CA_SEQ;
		
		private System.Nullable<int> _IKEY;
		
		private int _RENEW_EMAIL_SEND_FLAG;
		
		private int _FEE_FLAG;
		
		private string _CA_FROM;
		
		private string _Memo;
		
		private System.Nullable<System.DateTime> _USER_GET_CA_TIME;
		
		private string _Mailing_ADDRESS;
		
		private string _EIVO01;
		
		private System.Nullable<char> _FOR_CA_TYPE;
		
		private System.Nullable<char> _REC_CA_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCA_IDChanging(int value);
    partial void OnCA_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnPASSCODEChanging(string value);
    partial void OnPASSCODEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnJOB_TITLEChanging(string value);
    partial void OnJOB_TITLEChanged();
    partial void OnEMPLOYEE_IDChanging(string value);
    partial void OnEMPLOYEE_IDChanged();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnDUNSChanging(string value);
    partial void OnDUNSChanged();
    partial void OnAPPLY_STATEChanging(int value);
    partial void OnAPPLY_STATEChanged();
    partial void OnSEND_FLAGChanging(int value);
    partial void OnSEND_FLAGChanged();
    partial void OnERROR_CODEChanging(string value);
    partial void OnERROR_CODEChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnLOCALITYChanging(string value);
    partial void OnLOCALITYChanged();
    partial void OnCA_CLASS_IDChanging(int value);
    partial void OnCA_CLASS_IDChanged();
    partial void OnCREATION_TIMEChanging(System.DateTime value);
    partial void OnCREATION_TIMEChanged();
    partial void OnAPPLY_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnAPPLY_TIMEChanged();
    partial void OnCA_FALL_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCA_FALL_TIMEChanged();
    partial void OnMAIL_SEND_FLAGChanging(System.Nullable<bool> value);
    partial void OnMAIL_SEND_FLAGChanged();
    partial void OnERROR_SEND_MAIL_FLAGChanging(System.Nullable<bool> value);
    partial void OnERROR_SEND_MAIL_FLAGChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnUSER_SEXChanging(System.Nullable<int> value);
    partial void OnUSER_SEXChanged();
    partial void OnCOMPANY_NAMEChanging(string value);
    partial void OnCOMPANY_NAMEChanged();
    partial void OnCOMPANY_ADDRESSChanging(string value);
    partial void OnCOMPANY_ADDRESSChanged();
    partial void OnCOMPANY_TELChanging(string value);
    partial void OnCOMPANY_TELChanged();
    partial void OnCOMPANY_EXTENSIONChanging(string value);
    partial void OnCOMPANY_EXTENSIONChanged();
    partial void OnCOMPANY_FAXChanging(string value);
    partial void OnCOMPANY_FAXChanged();
    partial void OnINV_COMPANY_NAMEChanging(string value);
    partial void OnINV_COMPANY_NAMEChanged();
    partial void OnINV_COMPANY_ADDRESSChanging(string value);
    partial void OnINV_COMPANY_ADDRESSChanged();
    partial void OnINV_EMPLOYEE_IDChanging(string value);
    partial void OnINV_EMPLOYEE_IDChanged();
    partial void OnUSER_MOBILEChanging(string value);
    partial void OnUSER_MOBILEChanged();
    partial void OnUSER_BIRTHDAYChanging(System.Nullable<System.DateTime> value);
    partial void OnUSER_BIRTHDAYChanged();
    partial void OnCOMPANY_CLASSChanging(System.Nullable<short> value);
    partial void OnCOMPANY_CLASSChanged();
    partial void OnCHECKED_FLAGChanging(bool value);
    partial void OnCHECKED_FLAGChanged();
    partial void OnPIDChanging(string value);
    partial void OnPIDChanged();
    partial void OnCA_SEQChanging(string value);
    partial void OnCA_SEQChanged();
    partial void OnIKEYChanging(System.Nullable<int> value);
    partial void OnIKEYChanged();
    partial void OnRENEW_EMAIL_SEND_FLAGChanging(int value);
    partial void OnRENEW_EMAIL_SEND_FLAGChanged();
    partial void OnFEE_FLAGChanging(int value);
    partial void OnFEE_FLAGChanged();
    partial void OnCA_FROMChanging(string value);
    partial void OnCA_FROMChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnUSER_GET_CA_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUSER_GET_CA_TIMEChanged();
    partial void OnMailing_ADDRESSChanging(string value);
    partial void OnMailing_ADDRESSChanged();
    partial void OnEIVO01Changing(string value);
    partial void OnEIVO01Changed();
    partial void OnFOR_CA_TYPEChanging(System.Nullable<char> value);
    partial void OnFOR_CA_TYPEChanged();
    partial void OnREC_CA_TYPEChanging(System.Nullable<char> value);
    partial void OnREC_CA_TYPEChanged();
    #endregion
		
		public CA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CA_ID
		{
			get
			{
				return this._CA_ID;
			}
			set
			{
				if ((this._CA_ID != value))
				{
					this.OnCA_IDChanging(value);
					this.SendPropertyChanging();
					this._CA_ID = value;
					this.SendPropertyChanged("CA_ID");
					this.OnCA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSCODE
		{
			get
			{
				return this._PASSCODE;
			}
			set
			{
				if ((this._PASSCODE != value))
				{
					this.OnPASSCODEChanging(value);
					this.SendPropertyChanging();
					this._PASSCODE = value;
					this.SendPropertyChanged("PASSCODE");
					this.OnPASSCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(255)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_TITLE", DbType="VarChar(50)")]
		public string JOB_TITLE
		{
			get
			{
				return this._JOB_TITLE;
			}
			set
			{
				if ((this._JOB_TITLE != value))
				{
					this.OnJOB_TITLEChanging(value);
					this.SendPropertyChanging();
					this._JOB_TITLE = value;
					this.SendPropertyChanged("JOB_TITLE");
					this.OnJOB_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(30)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this.OnEMPLOYEE_IDChanging(value);
					this.SendPropertyChanging();
					this._EMPLOYEE_ID = value;
					this.SendPropertyChanged("EMPLOYEE_ID");
					this.OnEMPLOYEE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="Char(2)")]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUNS", DbType="VarChar(30)")]
		public string DUNS
		{
			get
			{
				return this._DUNS;
			}
			set
			{
				if ((this._DUNS != value))
				{
					this.OnDUNSChanging(value);
					this.SendPropertyChanging();
					this._DUNS = value;
					this.SendPropertyChanged("DUNS");
					this.OnDUNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLY_STATE", DbType="Int NOT NULL")]
		public int APPLY_STATE
		{
			get
			{
				return this._APPLY_STATE;
			}
			set
			{
				if ((this._APPLY_STATE != value))
				{
					this.OnAPPLY_STATEChanging(value);
					this.SendPropertyChanging();
					this._APPLY_STATE = value;
					this.SendPropertyChanged("APPLY_STATE");
					this.OnAPPLY_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEND_FLAG", DbType="Int NOT NULL")]
		public int SEND_FLAG
		{
			get
			{
				return this._SEND_FLAG;
			}
			set
			{
				if ((this._SEND_FLAG != value))
				{
					this.OnSEND_FLAGChanging(value);
					this.SendPropertyChanging();
					this._SEND_FLAG = value;
					this.SendPropertyChanged("SEND_FLAG");
					this.OnSEND_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERROR_CODE", DbType="VarChar(10)")]
		public string ERROR_CODE
		{
			get
			{
				return this._ERROR_CODE;
			}
			set
			{
				if ((this._ERROR_CODE != value))
				{
					this.OnERROR_CODEChanging(value);
					this.SendPropertyChanging();
					this._ERROR_CODE = value;
					this.SendPropertyChanged("ERROR_CODE");
					this.OnERROR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="VarChar(30)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCALITY", DbType="VarChar(30)")]
		public string LOCALITY
		{
			get
			{
				return this._LOCALITY;
			}
			set
			{
				if ((this._LOCALITY != value))
				{
					this.OnLOCALITYChanging(value);
					this.SendPropertyChanging();
					this._LOCALITY = value;
					this.SendPropertyChanged("LOCALITY");
					this.OnLOCALITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_CLASS_ID", DbType="Int NOT NULL")]
		public int CA_CLASS_ID
		{
			get
			{
				return this._CA_CLASS_ID;
			}
			set
			{
				if ((this._CA_CLASS_ID != value))
				{
					this.OnCA_CLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._CA_CLASS_ID = value;
					this.SendPropertyChanged("CA_CLASS_ID");
					this.OnCA_CLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime CREATION_TIME
		{
			get
			{
				return this._CREATION_TIME;
			}
			set
			{
				if ((this._CREATION_TIME != value))
				{
					this.OnCREATION_TIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATION_TIME = value;
					this.SendPropertyChanged("CREATION_TIME");
					this.OnCREATION_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLY_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> APPLY_TIME
		{
			get
			{
				return this._APPLY_TIME;
			}
			set
			{
				if ((this._APPLY_TIME != value))
				{
					this.OnAPPLY_TIMEChanging(value);
					this.SendPropertyChanging();
					this._APPLY_TIME = value;
					this.SendPropertyChanged("APPLY_TIME");
					this.OnAPPLY_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_FALL_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CA_FALL_TIME
		{
			get
			{
				return this._CA_FALL_TIME;
			}
			set
			{
				if ((this._CA_FALL_TIME != value))
				{
					this.OnCA_FALL_TIMEChanging(value);
					this.SendPropertyChanging();
					this._CA_FALL_TIME = value;
					this.SendPropertyChanged("CA_FALL_TIME");
					this.OnCA_FALL_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL_SEND_FLAG", DbType="Bit")]
		public System.Nullable<bool> MAIL_SEND_FLAG
		{
			get
			{
				return this._MAIL_SEND_FLAG;
			}
			set
			{
				if ((this._MAIL_SEND_FLAG != value))
				{
					this.OnMAIL_SEND_FLAGChanging(value);
					this.SendPropertyChanging();
					this._MAIL_SEND_FLAG = value;
					this.SendPropertyChanged("MAIL_SEND_FLAG");
					this.OnMAIL_SEND_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERROR_SEND_MAIL_FLAG", DbType="Bit")]
		public System.Nullable<bool> ERROR_SEND_MAIL_FLAG
		{
			get
			{
				return this._ERROR_SEND_MAIL_FLAG;
			}
			set
			{
				if ((this._ERROR_SEND_MAIL_FLAG != value))
				{
					this.OnERROR_SEND_MAIL_FLAGChanging(value);
					this.SendPropertyChanging();
					this._ERROR_SEND_MAIL_FLAG = value;
					this.SendPropertyChanged("ERROR_SEND_MAIL_FLAG");
					this.OnERROR_SEND_MAIL_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(30)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_SEX", DbType="Int")]
		public System.Nullable<int> USER_SEX
		{
			get
			{
				return this._USER_SEX;
			}
			set
			{
				if ((this._USER_SEX != value))
				{
					this.OnUSER_SEXChanging(value);
					this.SendPropertyChanging();
					this._USER_SEX = value;
					this.SendPropertyChanged("USER_SEX");
					this.OnUSER_SEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(255)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this.OnCOMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_NAME = value;
					this.SendPropertyChanged("COMPANY_NAME");
					this.OnCOMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_ADDRESS", DbType="VarChar(255)")]
		public string COMPANY_ADDRESS
		{
			get
			{
				return this._COMPANY_ADDRESS;
			}
			set
			{
				if ((this._COMPANY_ADDRESS != value))
				{
					this.OnCOMPANY_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_ADDRESS = value;
					this.SendPropertyChanged("COMPANY_ADDRESS");
					this.OnCOMPANY_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_TEL", DbType="VarChar(50)")]
		public string COMPANY_TEL
		{
			get
			{
				return this._COMPANY_TEL;
			}
			set
			{
				if ((this._COMPANY_TEL != value))
				{
					this.OnCOMPANY_TELChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_TEL = value;
					this.SendPropertyChanged("COMPANY_TEL");
					this.OnCOMPANY_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_EXTENSION", DbType="VarChar(10)")]
		public string COMPANY_EXTENSION
		{
			get
			{
				return this._COMPANY_EXTENSION;
			}
			set
			{
				if ((this._COMPANY_EXTENSION != value))
				{
					this.OnCOMPANY_EXTENSIONChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_EXTENSION = value;
					this.SendPropertyChanged("COMPANY_EXTENSION");
					this.OnCOMPANY_EXTENSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_FAX", DbType="VarChar(50)")]
		public string COMPANY_FAX
		{
			get
			{
				return this._COMPANY_FAX;
			}
			set
			{
				if ((this._COMPANY_FAX != value))
				{
					this.OnCOMPANY_FAXChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_FAX = value;
					this.SendPropertyChanged("COMPANY_FAX");
					this.OnCOMPANY_FAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_COMPANY_NAME", DbType="VarChar(255)")]
		public string INV_COMPANY_NAME
		{
			get
			{
				return this._INV_COMPANY_NAME;
			}
			set
			{
				if ((this._INV_COMPANY_NAME != value))
				{
					this.OnINV_COMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._INV_COMPANY_NAME = value;
					this.SendPropertyChanged("INV_COMPANY_NAME");
					this.OnINV_COMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_COMPANY_ADDRESS", DbType="VarChar(255)")]
		public string INV_COMPANY_ADDRESS
		{
			get
			{
				return this._INV_COMPANY_ADDRESS;
			}
			set
			{
				if ((this._INV_COMPANY_ADDRESS != value))
				{
					this.OnINV_COMPANY_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._INV_COMPANY_ADDRESS = value;
					this.SendPropertyChanged("INV_COMPANY_ADDRESS");
					this.OnINV_COMPANY_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_EMPLOYEE_ID", DbType="VarChar(30)")]
		public string INV_EMPLOYEE_ID
		{
			get
			{
				return this._INV_EMPLOYEE_ID;
			}
			set
			{
				if ((this._INV_EMPLOYEE_ID != value))
				{
					this.OnINV_EMPLOYEE_IDChanging(value);
					this.SendPropertyChanging();
					this._INV_EMPLOYEE_ID = value;
					this.SendPropertyChanged("INV_EMPLOYEE_ID");
					this.OnINV_EMPLOYEE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MOBILE", DbType="VarChar(50)")]
		public string USER_MOBILE
		{
			get
			{
				return this._USER_MOBILE;
			}
			set
			{
				if ((this._USER_MOBILE != value))
				{
					this.OnUSER_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._USER_MOBILE = value;
					this.SendPropertyChanged("USER_MOBILE");
					this.OnUSER_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_BIRTHDAY", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> USER_BIRTHDAY
		{
			get
			{
				return this._USER_BIRTHDAY;
			}
			set
			{
				if ((this._USER_BIRTHDAY != value))
				{
					this.OnUSER_BIRTHDAYChanging(value);
					this.SendPropertyChanging();
					this._USER_BIRTHDAY = value;
					this.SendPropertyChanged("USER_BIRTHDAY");
					this.OnUSER_BIRTHDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_CLASS", DbType="SmallInt")]
		public System.Nullable<short> COMPANY_CLASS
		{
			get
			{
				return this._COMPANY_CLASS;
			}
			set
			{
				if ((this._COMPANY_CLASS != value))
				{
					this.OnCOMPANY_CLASSChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_CLASS = value;
					this.SendPropertyChanged("COMPANY_CLASS");
					this.OnCOMPANY_CLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKED_FLAG", DbType="Bit NOT NULL")]
		public bool CHECKED_FLAG
		{
			get
			{
				return this._CHECKED_FLAG;
			}
			set
			{
				if ((this._CHECKED_FLAG != value))
				{
					this.OnCHECKED_FLAGChanging(value);
					this.SendPropertyChanging();
					this._CHECKED_FLAG = value;
					this.SendPropertyChanged("CHECKED_FLAG");
					this.OnCHECKED_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Char(10)")]
		public string PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_SEQ", DbType="VarChar(50)")]
		public string CA_SEQ
		{
			get
			{
				return this._CA_SEQ;
			}
			set
			{
				if ((this._CA_SEQ != value))
				{
					this.OnCA_SEQChanging(value);
					this.SendPropertyChanging();
					this._CA_SEQ = value;
					this.SendPropertyChanged("CA_SEQ");
					this.OnCA_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IKEY", DbType="Int")]
		public System.Nullable<int> IKEY
		{
			get
			{
				return this._IKEY;
			}
			set
			{
				if ((this._IKEY != value))
				{
					this.OnIKEYChanging(value);
					this.SendPropertyChanging();
					this._IKEY = value;
					this.SendPropertyChanged("IKEY");
					this.OnIKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RENEW_EMAIL_SEND_FLAG", DbType="Int NOT NULL")]
		public int RENEW_EMAIL_SEND_FLAG
		{
			get
			{
				return this._RENEW_EMAIL_SEND_FLAG;
			}
			set
			{
				if ((this._RENEW_EMAIL_SEND_FLAG != value))
				{
					this.OnRENEW_EMAIL_SEND_FLAGChanging(value);
					this.SendPropertyChanging();
					this._RENEW_EMAIL_SEND_FLAG = value;
					this.SendPropertyChanged("RENEW_EMAIL_SEND_FLAG");
					this.OnRENEW_EMAIL_SEND_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEE_FLAG", DbType="Int NOT NULL")]
		public int FEE_FLAG
		{
			get
			{
				return this._FEE_FLAG;
			}
			set
			{
				if ((this._FEE_FLAG != value))
				{
					this.OnFEE_FLAGChanging(value);
					this.SendPropertyChanging();
					this._FEE_FLAG = value;
					this.SendPropertyChanged("FEE_FLAG");
					this.OnFEE_FLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_FROM", DbType="NVarChar(50)")]
		public string CA_FROM
		{
			get
			{
				return this._CA_FROM;
			}
			set
			{
				if ((this._CA_FROM != value))
				{
					this.OnCA_FROMChanging(value);
					this.SendPropertyChanging();
					this._CA_FROM = value;
					this.SendPropertyChanged("CA_FROM");
					this.OnCA_FROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(255)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_GET_CA_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> USER_GET_CA_TIME
		{
			get
			{
				return this._USER_GET_CA_TIME;
			}
			set
			{
				if ((this._USER_GET_CA_TIME != value))
				{
					this.OnUSER_GET_CA_TIMEChanging(value);
					this.SendPropertyChanging();
					this._USER_GET_CA_TIME = value;
					this.SendPropertyChanged("USER_GET_CA_TIME");
					this.OnUSER_GET_CA_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mailing_ADDRESS", DbType="VarChar(100)")]
		public string Mailing_ADDRESS
		{
			get
			{
				return this._Mailing_ADDRESS;
			}
			set
			{
				if ((this._Mailing_ADDRESS != value))
				{
					this.OnMailing_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._Mailing_ADDRESS = value;
					this.SendPropertyChanged("Mailing_ADDRESS");
					this.OnMailing_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EIVO01", DbType="NVarChar(1)")]
		public string EIVO01
		{
			get
			{
				return this._EIVO01;
			}
			set
			{
				if ((this._EIVO01 != value))
				{
					this.OnEIVO01Changing(value);
					this.SendPropertyChanging();
					this._EIVO01 = value;
					this.SendPropertyChanged("EIVO01");
					this.OnEIVO01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOR_CA_TYPE", DbType="Char(1)")]
		public System.Nullable<char> FOR_CA_TYPE
		{
			get
			{
				return this._FOR_CA_TYPE;
			}
			set
			{
				if ((this._FOR_CA_TYPE != value))
				{
					this.OnFOR_CA_TYPEChanging(value);
					this.SendPropertyChanging();
					this._FOR_CA_TYPE = value;
					this.SendPropertyChanged("FOR_CA_TYPE");
					this.OnFOR_CA_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REC_CA_TYPE", DbType="Char(1)")]
		public System.Nullable<char> REC_CA_TYPE
		{
			get
			{
				return this._REC_CA_TYPE;
			}
			set
			{
				if ((this._REC_CA_TYPE != value))
				{
					this.OnREC_CA_TYPEChanging(value);
					this.SendPropertyChanging();
					this._REC_CA_TYPE = value;
					this.SendPropertyChanged("REC_CA_TYPE");
					this.OnREC_CA_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CA_TEMP")]
	public partial class CA_TEMP
	{
		
		private string _First_Name;
		
		private string _User_Name;
		
		private System.Nullable<int> _User_Sex;
		
		private System.Nullable<System.DateTime> _User_Birth;
		
		private string _Company_Name;
		
		private string _Company_Address;
		
		private string _Company_Tel;
		
		private string _Company_Extention;
		
		private string _Company_Fax;
		
		private string _User_Mobile;
		
		private string _User_Pid;
		
		private string _Email;
		
		private string _Job_Title;
		
		private string _Employee_ID;
		
		private string _Country;
		
		private string _Duns;
		
		private System.DateTime _Creat_Time;
		
		private System.Nullable<int> _ikey;
		
		private string _Operator;
		
		private System.Nullable<int> _Send_Mail_Flag;
		
		private string _Mailing_ADDRESS;
		
		public CA_TEMP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="VarChar(50)")]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this._User_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Sex", DbType="Int")]
		public System.Nullable<int> User_Sex
		{
			get
			{
				return this._User_Sex;
			}
			set
			{
				if ((this._User_Sex != value))
				{
					this._User_Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Birth", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> User_Birth
		{
			get
			{
				return this._User_Birth;
			}
			set
			{
				if ((this._User_Birth != value))
				{
					this._User_Birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Name", DbType="VarChar(255)")]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this._Company_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Address", DbType="VarChar(255)")]
		public string Company_Address
		{
			get
			{
				return this._Company_Address;
			}
			set
			{
				if ((this._Company_Address != value))
				{
					this._Company_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Tel", DbType="VarChar(50)")]
		public string Company_Tel
		{
			get
			{
				return this._Company_Tel;
			}
			set
			{
				if ((this._Company_Tel != value))
				{
					this._Company_Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Extention", DbType="VarChar(50)")]
		public string Company_Extention
		{
			get
			{
				return this._Company_Extention;
			}
			set
			{
				if ((this._Company_Extention != value))
				{
					this._Company_Extention = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Fax", DbType="VarChar(50)")]
		public string Company_Fax
		{
			get
			{
				return this._Company_Fax;
			}
			set
			{
				if ((this._Company_Fax != value))
				{
					this._Company_Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Mobile", DbType="VarChar(50)")]
		public string User_Mobile
		{
			get
			{
				return this._User_Mobile;
			}
			set
			{
				if ((this._User_Mobile != value))
				{
					this._User_Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Pid", DbType="VarChar(50)")]
		public string User_Pid
		{
			get
			{
				return this._User_Pid;
			}
			set
			{
				if ((this._User_Pid != value))
				{
					this._User_Pid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_Title", DbType="VarChar(50)")]
		public string Job_Title
		{
			get
			{
				return this._Job_Title;
			}
			set
			{
				if ((this._Job_Title != value))
				{
					this._Job_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="VarChar(60)")]
		public string Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this._Employee_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(10)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duns", DbType="VarChar(20)")]
		public string Duns
		{
			get
			{
				return this._Duns;
			}
			set
			{
				if ((this._Duns != value))
				{
					this._Duns = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creat_Time", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Creat_Time
		{
			get
			{
				return this._Creat_Time;
			}
			set
			{
				if ((this._Creat_Time != value))
				{
					this._Creat_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ikey", DbType="Int")]
		public System.Nullable<int> ikey
		{
			get
			{
				return this._ikey;
			}
			set
			{
				if ((this._ikey != value))
				{
					this._ikey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(10)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Mail_Flag", DbType="Int")]
		public System.Nullable<int> Send_Mail_Flag
		{
			get
			{
				return this._Send_Mail_Flag;
			}
			set
			{
				if ((this._Send_Mail_Flag != value))
				{
					this._Send_Mail_Flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mailing_ADDRESS", DbType="VarChar(100)")]
		public string Mailing_ADDRESS
		{
			get
			{
				return this._Mailing_ADDRESS;
			}
			set
			{
				if ((this._Mailing_ADDRESS != value))
				{
					this._Mailing_ADDRESS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
