<?xml version="1.0" encoding="utf-8"?>
<Database Name="DigitalContractTest" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CDS_Document" Member="CDS_Document">
    <Type Name="CDS_Document">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Contract_CDS_Document" Member="Contract" ThisKey="DocID" OtherKey="ContractID" Type="Contract" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_DocumentProcessLog_CDS_Document" Member="DocumentProcessLog" ThisKey="DocID" OtherKey="DocID" Type="DocumentProcessLog" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CHT_Token" Member="CHT_Token">
    <Type Name="CHT_Token">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ClusterID" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationKey" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ThirdPartyClusterID" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="FK_CHT_Token_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contract" Member="Contract">
    <Type Name="Contract">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ContractNo" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ContractContent" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPassStamp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserInProgress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NotifyUntilDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Contract_CDS_Document" Member="CDS_Document" ThisKey="ContractID" OtherKey="DocID" Type="CDS_Document" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_Contract_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" />
      <Association Name="FK_Contract_UserProfile" Member="UserProfile" ThisKey="CreateUID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="FK_ContractingParty_Contract" Member="ContractingParty" ThisKey="ContractID" OtherKey="ContractID" Type="ContractingParty" DeleteRule="CASCADE" />
      <Association Name="FK_ContractingUser_Contract" Member="ContractingUser" ThisKey="ContractID" OtherKey="ContractID" Type="ContractingUser" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractNoteRequest_Contract" Member="ContractNoteRequest" ThisKey="ContractID" OtherKey="ContractID" Type="ContractNoteRequest" DeleteRule="CASCADE" />
      <Association Name="FK_ContractSealRequest_Contract" Member="ContractSealRequest" ThisKey="ContractID" OtherKey="ContractID" Type="ContractSealRequest" DeleteRule="CASCADE" />
      <Association Name="FK_ContractSignature_Contract" Member="ContractSignature" ThisKey="ContractID" OtherKey="ContractID" Type="ContractSignature" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_ContractSignaturePositionRequest_Contract" Member="ContractSignaturePositionRequest" ThisKey="ContractID" OtherKey="ContractID" Type="ContractSignaturePositionRequest" DeleteRule="CASCADE" />
      <Association Name="FK_ContractSignatureRequest_Contract" Member="ContractSignatureRequest" ThisKey="ContractID" OtherKey="ContractID" Type="ContractSignatureRequest" DeleteRule="CASCADE" />
      <Association Name="FK_ContractUserSignature_Contract" Member="ContractUserSignature" ThisKey="ContractID" OtherKey="ContractID" Type="ContractUserSignature" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_ContractUserSignatureRequest_Contract" Member="ContractUserSignatureRequest" ThisKey="ContractID" OtherKey="ContractID" Type="ContractUserSignatureRequest" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ContractingIntent" Member="ContractingIntent">
    <Type Name="ContractingIntent">
      <Column Name="IntentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="FK_ContractingParty_ContractingIntent" Member="ContractingParty" ThisKey="IntentID" OtherKey="IntentID" Type="ContractingParty" DeleteRule="NO ACTION" />
      <Association Name="FK_SealTemplate_ContractingIntent" Member="SealTemplate" ThisKey="IntentID" OtherKey="IntentID" Type="SealTemplate" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.ContractingParty" Member="ContractingParty">
    <Type Name="ContractingParty">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IntentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsInitiator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FK_ContractingParty_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractingParty_ContractingIntent" Member="ContractingIntent" ThisKey="IntentID" OtherKey="IntentID" Type="ContractingIntent" IsForeignKey="true" />
      <Association Name="FK_ContractingParty_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractingUser" Member="ContractingUser">
    <Type Name="ContractingUser">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_ContractingUser_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" />
      <Association Name="FK_ContractingUser_UserProfile" Member="UserProfile" ThisKey="UserID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="FK_ContractUserSignatureRequest_ContractingUser" Member="ContractUserSignatureRequest" ThisKey="ContractID,UserID" OtherKey="ContractID,UserID" Type="ContractUserSignatureRequest" Cardinality="One" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.ContractNoteRequest" Member="ContractNoteRequest">
    <Type Name="ContractNoteRequest">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StampDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StampUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SealScale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginLeft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_ContractNoteRequest_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractNoteRequest_UserProfile" Member="UserProfile" ThisKey="StampUID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractSealRequest" Member="ContractSealRequest">
    <Type Name="ContractSealRequest">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SealID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StampDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SealImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StampUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SealScale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginLeft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_ContractSealRequest_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractSealRequest_SealTemplate" Member="SealTemplate" ThisKey="SealID" OtherKey="SealID" Type="SealTemplate" IsForeignKey="true" />
      <Association Name="FK_ContractSealRequest_UserProfile" Member="UserProfile" ThisKey="StampUID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractSignature" Member="ContractSignature">
    <Type Name="ContractSignature">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_ContractSignature_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractSignature_ContractSignatureRequest" Member="ContractSignatureRequest" ThisKey="ContractID,CompanyID" OtherKey="ContractID,CompanyID" Type="ContractSignatureRequest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractSignaturePositionRequest" Member="ContractSignaturePositionRequest">
    <Type Name="ContractSignaturePositionRequest">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContractorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PositionID" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ScaleWidth" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ScaleHeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginLeft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_ContractSignaturePositionRequest_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractSignaturePositionRequest_Organization" Member="Organization" ThisKey="ContractorID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" />
      <Association Name="FK_ContractSignaturePositionRequest_UserProfile" Member="UserProfile" ThisKey="OperatorID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractSignatureRequest" Member="ContractSignatureRequest">
    <Type Name="ContractSignatureRequest">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SignerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SignatureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ResponsePath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SealScale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SealImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MarginTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginLeft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StampDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestTicket" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="FK_ContractSignature_ContractSignatureRequest" Member="ContractSignature" ThisKey="ContractID,CompanyID" OtherKey="ContractID,CompanyID" Type="ContractSignature" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSignatureRequest_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractSignatureRequest_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" />
      <Association Name="FK_ContractSignatureRequest_UserProfile" Member="UserProfile" ThisKey="SignerID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractUserSignature" Member="ContractUserSignature">
    <Type Name="ContractUserSignature">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_ContractUserSignature_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractUserSignature_ContractUserSignatureRequest" Member="ContractUserSignatureRequest" ThisKey="ContractID,UserID" OtherKey="ContractID,UserID" Type="ContractUserSignatureRequest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContractUserSignatureRequest" Member="ContractUserSignatureRequest">
    <Type Name="ContractUserSignatureRequest">
      <Column Name="ContractID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SignerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SignatureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ResponsePath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SealScale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SealImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MarginTop" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarginLeft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PageIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StampDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestTicket" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="SignatureDone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FK_ContractUserSignature_ContractUserSignatureRequest" Member="ContractUserSignature" ThisKey="ContractID,UserID" OtherKey="ContractID,UserID" Type="ContractUserSignature" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractUserSignatureRequest_Contract" Member="Contract" ThisKey="ContractID" OtherKey="ContractID" Type="Contract" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_ContractUserSignatureRequest_ContractingUser" Member="ContractingUser" ThisKey="ContractID,UserID" OtherKey="ContractID,UserID" Type="ContractingUser" IsForeignKey="true" />
      <Association Name="FK_ContractUserSignatureRequest_UserProfile" Member="UserProfile" ThisKey="UserID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentProcessLog" Member="DocumentProcessLog">
    <Type Name="DocumentProcessLog">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StepID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientDevice" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Association Name="FK_DocumentProcessLog_CDS_Document" Member="CDS_Document" ThisKey="DocID" OtherKey="DocID" Type="CDS_Document" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_DocumentProcessLog_UserProfile" Member="UserProfile" ThisKey="ActorID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdentityCert" Member="IdentityCert">
    <Type Name="IdentityCert">
      <Column Name="SeqNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="X509Certificate" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CertificateType" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BindingUID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_IdentityCert_UserProfile" Member="UserProfile" ThisKey="BindingUID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organization" Member="Organization">
    <Type Name="Organization">
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LogoURL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ContactFax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ContactMobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegAddr" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="UndertakerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Addr" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnglishAddr" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EnglishRegAddr" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ContactEmail" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="UndertakerPhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UndertakerFax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UndertakerMobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceSignature" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="UndertakerID" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="CompanyBelongTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CanCreateContract" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FK_CHT_Token_Organization" Member="CHT_Token" ThisKey="CompanyID" OtherKey="CompanyID" Type="CHT_Token" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_Contract_Organization" Member="Contract" ThisKey="CompanyID" OtherKey="CompanyID" Type="Contract" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractingParty_Organization" Member="ContractingParty" ThisKey="CompanyID" OtherKey="CompanyID" Type="ContractingParty" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSignaturePositionRequest_Organization" Member="ContractSignaturePositionRequest" ThisKey="CompanyID" OtherKey="ContractorID" Type="ContractSignaturePositionRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSignatureRequest_Organization" Member="ContractSignatureRequest" ThisKey="CompanyID" OtherKey="CompanyID" Type="ContractSignatureRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_OrganizationStatus_Organization" Member="OrganizationStatus" ThisKey="CompanyID" OtherKey="CompanyID" Type="OrganizationStatus" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_OrganizationToken_Organization" Member="OrganizationToken" ThisKey="CompanyID" OtherKey="CompanyID" Type="OrganizationToken" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_OrganizationUser_Organization" Member="OrganizationUser" ThisKey="CompanyID" OtherKey="CompanyID" Type="OrganizationUser" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.OrganizationStatus" Member="OrganizationStatus">
    <Type Name="OrganizationStatus">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_OrganizationStatus_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrganizationToken" Member="OrganizationToken">
    <Type Name="OrganizationToken">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="X509Certificate" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Thumbprint" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="PKCS12" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KeyID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FK_OrganizationToken_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrganizationUser" Member="OrganizationUser">
    <Type Name="OrganizationUser">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_OrganizationUser_Organization" Member="Organization" ThisKey="CompanyID" OtherKey="CompanyID" Type="Organization" IsForeignKey="true" />
      <Association Name="FK_OrganizationUser_UserProfile" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SealTemplate" Member="SealTemplate">
    <Type Name="SealTemplate">
      <Column Name="SealID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Intent" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IntentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SealImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FK_ContractSealRequest_SealTemplate" Member="ContractSealRequest" ThisKey="SealID" OtherKey="SealID" Type="ContractSealRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_SealTemplate_ContractingIntent" Member="ContractingIntent" ThisKey="IntentID" OtherKey="IntentID" Type="ContractingIntent" IsForeignKey="true" />
      <Association Name="FK_SealTemplate_UserProfile" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfile">
    <Type Name="UserProfile">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="PID" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Expiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThemeName" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Password2" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="MailID" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="LoginFailedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PasswordUpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OperatorNote" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OperatorOwnerUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorReceiptNo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="FK_Contract_UserProfile" Member="Contract" ThisKey="UID" OtherKey="CreateUID" Type="Contract" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractingUser_UserProfile" Member="ContractingUser" ThisKey="UID" OtherKey="UserID" Type="ContractingUser" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractNoteRequest_UserProfile" Member="ContractNoteRequest" ThisKey="UID" OtherKey="StampUID" Type="ContractNoteRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSealRequest_UserProfile" Member="ContractSealRequest" ThisKey="UID" OtherKey="StampUID" Type="ContractSealRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSignaturePositionRequest_UserProfile" Member="ContractSignaturePositionRequest" ThisKey="UID" OtherKey="OperatorID" Type="ContractSignaturePositionRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractSignatureRequest_UserProfile" Member="ContractSignatureRequest" ThisKey="UID" OtherKey="SignerID" Type="ContractSignatureRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_ContractUserSignatureRequest_UserProfile" Member="ContractUserSignatureRequest" ThisKey="UID" OtherKey="UserID" Type="ContractUserSignatureRequest" DeleteRule="NO ACTION" />
      <Association Name="FK_DocumentProcessLog_UserProfile" Member="DocumentProcessLog" ThisKey="UID" OtherKey="ActorID" Type="DocumentProcessLog" DeleteRule="NO ACTION" />
      <Association Name="FK_IdentityCert_UserProfile" Member="IdentityCert" ThisKey="UID" OtherKey="BindingUID" Type="IdentityCert" DeleteRule="NO ACTION" />
      <Association Name="FK_OrganizationUser_UserProfile" Member="OrganizationUser" ThisKey="UID" OtherKey="UID" Type="OrganizationUser" Cardinality="One" DeleteRule="CASCADE" />
      <Association Name="FK_SealTemplate_UserProfile" Member="SealTemplate" ThisKey="UID" OtherKey="UID" Type="SealTemplate" DeleteRule="NO ACTION" />
      <Association Name="FK_UserProfile_UserProfile" Member="CreatorUserProfile" ThisKey="Creator" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="FK_UserProfile_UserProfile" Member="UserProfile_UserProfile" ThisKey="UID" OtherKey="Creator" Type="UserProfile" DeleteRule="NO ACTION" />
      <Association Name="FK_UserProfile_UserProfile1" Member="Auth" ThisKey="AuthID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="FK_UserProfile_UserProfile1" Member="UserProfile_UserProfile1" ThisKey="UID" OtherKey="AuthID" Type="UserProfile" DeleteRule="NO ACTION" />
      <Association Name="FK_UserRole_UserProfile" Member="UserRole" ThisKey="UID" OtherKey="UID" Type="UserRole" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRole">
    <Type Name="UserRole">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_UserRole_UserProfile" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_UserRole_UserRoleDefinition" Member="UserRoleDefinition" ThisKey="RoleID" OtherKey="RoleID" Type="UserRoleDefinition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoleDefinition" Member="UserRoleDefinition">
    <Type Name="UserRoleDefinition">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="FK_UserRole_UserRoleDefinition" Member="UserRole" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" DeleteRule="NO ACTION" />
    </Type>
  </Table>
</Database>